pipeline {
    agent any
    environment {
        SECRET_KEY = credentials('SECRET_KEY')
        DATABASE_URI = credentials('DATABASE_URI')
    }
    stages {
            stage('Setup'){
              // Comment Here
                steps{
                sh """sudo apt install python3-venv -y 
                python3 -m venv venv
                . ./venv/bin/activate
                pip3 install -r requirements.txt
                """
                }
            }
             stage('Build'){
              // Comment Here
                steps{
                sh   
                }
            }
            stage('Testing'){
              // Comment Here
                steps{
                sh """ . ./venv/bin/activate
                python3 -m pytest --junitxml unittests.xml
                python3 -m pytest --cov-report xml:coverage.xml --cov=tests/
                deactivate
                rm -rf /venv"""    
                }
            }
            stage('Deploy'){
              // Comment Here
                steps{
                sh    
                }
            }
            stage('Post Build'){
              // Comment Here
                steps{
                sh    
                }
            }
        }
}
