pipeline {
    agent any
    environment {
        JOB_NAME = Vinyl Island App
        BUILD_NUMBER = 1.0
        BUILD_URL = 
        SECRET_KEY = credentials('SECRET_KEY')
        DATABASE_URI = credentials('DATABASE_URI')
    }
    stages {
            stage('Installing Packages'){
              // Comment Here
                steps{
                sh """sudo apt install python3-venv -y 
                python3 -m venv venv
                . ./venv/bin/activate
                pip3 install -r requirements.txt
                """
                }
            }
             stage('Build'){
              // Comment Here
                steps{
                      sh 'python --version'
                }
            }
            stage('Static Code Checking') {
            steps {
                script {
                    sh 'find . -name \\*.py | xargs pylint --load-plugins=pylint_django -f parseable | tee pylint.log'
                    recordIssues(
                        tool: pyLint(pattern: 'pylint.log'),
                        failTotalHigh: 10,
                    )
                }
              }
            }
            stage('Running Unit Tests'){
              // Comment Here
                steps{
                sh """ . ./venv/bin/activate
                python3 -m pytest --junitxml unittests.xml
                python3 -m pytest --cov-report xml:coverage.xml --cov=tests/
                deactivate
                rm -rf /venv"""    
                }
            }
            stage('Deploy'){
              // Comment Here
                steps{
                  echo 'ready to deploy'
                }
            }
            stage('Post Build'){
              // Comment Here
                steps{
                  echo 'post build actions'
                }
            }
        }
}
